
unit lodlg;
interface

{
  Automatically converted by H2Pas 1.0.0 from D:\work\FPC\ooi\lodlg.tmp.h
  The following command line parameters were used:
    -e
    -p
    -D
    -v
    -w
    -o
  And handmade update after it.
}

  { Copyright (c) 2001, 2010, Oracle and/or its affiliates. All rights reserved.  }

  const
     SCC_PACK_SET = 1;
     SCC_PACKED_BY_LODLG_H = 1;

  const
     BUTTON_CANCEL = 101;     
     BUTTON_HELP = 102;     
     BUTTON_MORE_DISPLAY = 103;     
     BUTTON_CHANGEDISPLAY = 104;     
     BUTTON_CHANGEHEADER = 105;     
     BUTTON_REBUILD = 106;     
     BUTTON_WRITE = 107;     
     BUTTON_JOBPROPERTIES = 108;     
     BUTTON_MORE_CLIPBOARD = 109;     
     BUTTON_MORE_PRINT = 110;     
     BUTTON_CHANGEPRINT = 111;     
     BUTTON_CHANGECLIPBOARD = 112;     
     BUTTON_SKIP = 116;     
     BUTTON_RENAME = 117;     
     BUTTON_ALL = 118;     
     STATIC_PRINTING = 201;     
     STATIC_FILE = 202;     
     STATIC_ON = 203;     
     STATIC_DEVICE = 204;     
     STATIC_CONNECTED = 205;     
     STATIC_PORT = 206;     
     STATIC_TOP = 209;     
     STATIC_BOTTOM = 210;     
     STATIC_LEFT = 211;     
     STATIC_RIGHT = 212;     
     STATIC_PAGELAYOUT = 214;     
     STATIC_SAMPLE = 215;     
     STATIC_HEADERFONT = 222;     
     STATIC_DISPLAYFONT = 224;     
     STATIC_DISPLAYFONTBOX = 223;     
     STATIC_HEADERFONTBOX = 225;     
     STATIC_JOBNAME = 226;     
     STATIC_JOBNAMEHELP = 227;     
     STATIC_VIEWASBOX = 228;     
     STATIC_TEXTTOFIND = 229;     
     STATIC_FILTERINFO = 230;     
     STATIC_RTFEXTRA = 231;     
     STATIC_PRINTFONT = 232;     
     STATIC_PRINTFONTBOX = 233;     
     STATIC_CLIPBOARDFONT = 234;
     STATIC_CLIPBOARDFONTBOX = 235;     
     STATIC_CHOOSEDIRMSG = 236;     
     STATIC_STOREDDIRSBOX = 237;     
     STATIC_PROGRESSRECT = 238;     
     STATIC_PROGRESSTEXT = 239;     
     STATIC_ARCSORTORDER = 240;     
     STATIC_DOCMARGINSBOX = 241;     
     STATIC_ENCODINGBOX = 242;     
     STATIC_SSPRINTMODEBOX = 243;     
     STATIC_DBPRINTMODEBOX = 244;     
     STATIC_BADNAME_NAMEBOX = 251;     
     STATIC_BADNAME_NAMEEDIT = 252;     
     STATIC_PARENFILE = 253;     
     STATIC_WARNING = 254;     
     RADIO_TEXTANSI7 = 301;     
     RADIO_TEXTANSI8 = 302;     
     RADIO_TEXTDOS7 = 303;     
     RADIO_TEXTDOS8 = 304;     
     RADIO_TEXTUNICODE = 305;     
     RADIO_HEX = 306;     
     RADIO_DONOTVIEW = 307;     
     RADIO_BMPORIGINALASPECT = 308;     
     RADIO_BMPSTRETCHTOMARGINS = 309;     
     RADIO_VECSTRETCHTOMARGINS = 310;     
     RADIO_VECORIGINALASPECT = 311;     
     RADIO_FORWARD = 312;     
     RADIO_BACKWARD = 313;     
     RADIO_SSCOPYASTABLE = 314;     
     RADIO_SSCOPYUSINGOTABS = 315;     
     RADIO_SSCOPYUSINGTABS = 316;     
     RADIO_DBCOPYASTABLE = 317;     
     RADIO_DBCOPYUSINGOTABS = 318;     
     RADIO_DBCOPYUSINGTABS = 319;     
     RADIO_SORTNONE = 320;     
     RADIO_SORTNAME = 321;     
     RADIO_SORTSIZE = 322;     
     RADIO_SORTDATE = 323;     
     RADIO_PRINTALL = 324;     
     RADIO_PRINTSELECT = 325;     
     RADIO_PRINTPAGES = 326;     
     RADIO_IGNOREDIR = 327;
     RADIO_RESTOREDIR = 328;     
     RADIO_SORTASCENDING = 329;     
     RADIO_SORTDESCENDING = 330;     
     RADIO_TEXTSHIFTJIS = 331;     
     RADIO_TEXTBIG5 = 332;     
     RADIO_TEXTHANGUL = 333;     
     RADIO_TEXTGB = 334;     
     RADIO_JAPANEUC = 335;     
     RADIO_CYRILLIC1251 = 336;     
     RADIO_CYRILLICKOI8 = 337;     
     RADIO_TEXTLATIN2 = 338;     
     RADIO_TEXT = 339;     
     RADIO_TEXTMAC = 340;     
     RADIO_SSPRINTNOSCALE = 341;     
     RADIO_SSPRINTFITTOPAGE = 342;     
     RADIO_SSPRINTFITTOHEIGHT = 343;     
     RADIO_SSPRINTFITTOWIDTH = 344;     
     RADIO_DBPRINTNOSCALE = 345;     
     RADIO_DBPRINTFITTOPAGE = 346;     
     RADIO_DBPRINTFITTOHEIGHT = 347;     
     RADIO_DBPRINTFITTOWIDTH = 348;     
     RADIO_SSPRINTSCALETO = 349;     
     RADIO_SSPRINTFITTO = 350;     
     RADIO_SSPRINTACROSS = 351;     
     RADIO_SSPRINTDOWN = 352;     
     RADIO_JAPANJIS = 353;     
     RADIO_CENTRALEU1250 = 354;     
     RADIO_REPLACE = 355;     
     RADIO_SKIP = 356;     
     RADIO_GEN = 357;     
     RADIO_CREATE = 358;     
     RADIO_2DIGITYEARS = 359;     
     RADIO_4DIGITYEARS = 360;     
     RADIO_REGISTRYYEARS = 361;     
     RADIO_UTF8 = 362;     
     BOX_PRINTHEADER = 401;     
     BOX_SSPRINTGRIDLINES = 402;     
     BOX_SSPRINTHEADINGS = 403;     
     BOX_DBPRINTGRIDLINES = 404;     
     BOX_DBPRINTHEADINGS = 405;     
     BOX_SSSHOWGRIDLINES = 407;
     BOX_DBSHOWGRIDLINES = 408;     
     BOX_BMPPRINTBORDER = 406;     
     BOX_VECPRINTBORDER = 412;     
     BOX_MATCHCASE = 413;     
     BOX_CLIPTEXT = 414;     
     BOX_CLIPRICHTEXT = 415;     
     BOX_CLIPAMI2 = 416;     
     BOX_CLIPAMI = 417;     
     BOX_CLIPPROWRITEPLUS = 418;     
     BOX_CLIPWORDSTAR = 419;     
     BOX_CLIPLEGACY = 420;     
     BOX_CLIPBITMAP = 421;     
     BOX_CLIPDIB = 422;     
     BOX_CLIPMETAFILE = 423;     
     BOX_CLIPPALETTE = 424;     
     BOX_DBFIELDNAMESTOCLIP = 425;     
     BOX_PRINTCOLLATE = 426;     
     BOX_USEDOCMARGINS = 427;     
     BOX_CLIPUNICODE = 428;     
     BOX_ANTIALIAS = 429;     
     EDIT_TOP = 501;     
     EDIT_BOTTOM = 502;     
     EDIT_LEFT = 503;     
     EDIT_RIGHT = 504;     
     EDIT_JOBNAME = 505;     
     EDIT_TEXTTOFIND = 506;     
     EDIT_PRINTCOPIES = 507;     
     EDIT_PRINTFIRSTPAGE = 508;     
     EDIT_PRINTLASTPAGE = 509;     
     EDIT_SSPRINTSCALEPERCENT = 510;     
     EDIT_SSPRINTSCALEWIDE = 511;     
     EDIT_SSPRINTSCALEHIGH = 512;     
     EDIT_BADNAMETEXT = 513;     
     MSCROLL_TOP = 601;     
     MSCROLL_BOTTOM = 602;     
     MSCROLL_LEFT = 603;     
     MSCROLL_RIGHT = 604;     
     MSCROLL_PERCENT = 605;     
     MSCROLL_WIDE = 606;     
     MSCROLL_HIGH = 607;     
     LIST_FILTERS = 700;
     LIST_AVAILABLEPRINTERS = 701;     
     SCCLO_PRINTABORTDIALOG = 1000;     
     SCCLO_CDPRINTDLG = 1001;     
     SCCLO_PRINTOPTIONSDIALOG = 1002;     
     SCCLO_DISPLAYOPTIONSDIALOG = 1003;     
     SCCLO_PRINTMOREDIALOG = 1004;     
     SCCLO_DISPLAYMOREDIALOG = 1005;     
     SCCLO_SEARCHDIALOG = 1006;     
     SCCLO_CLIPBOARDOPTIONSDIALOG = 1007;     
     SCCLO_CLIPBOARDMOREDIALOG = 1008;     
     SCCLO_FILTERLISTDIALOG = 1009;     
     SCCLO_PRINTOPTIONSPAGE = 1010;     
     SCCLO_CLIPBOARDOPTIONSPAGE = 1011;     
     SCCLO_DISPLAYOPTIONSPAGE = 1012;     
     SCCLO_ARCSAVEDLGTEMPLATE = 1013;     
     SCCLO_PROGRESSDIALOG = 1014;     
     SCCLO_CDPRINTDLG95 = 1015;     
     SCCLO_ARCBADNAMEDIALOG = 1023;     
     SCCLO_ARCILLEGALCHARDIALOG = 1024;

implementation


end.
