unit sccerrUnit;
interface
uses scctype;
{
  Automatically converted by H2Pas 1.0.0 from D:\work\FPC\ooi\sccerr.tmp.h
  The following command line parameters were used:
    -e
    -p
    -D
    -v
    -w
    -o
  And handmade update after it.
}

  { Pointers to basic pascal types, inserted by h2pas conversion program.}
  Type
  SCCERR = VTDWORD;
  PSCCERR  = ^SCCERR;


  { Copyright (c) 2001, 2010, Oracle and/or its affiliates. All rights reserved.  }
  {
    |  Outside In Viewer Technology - Include
    |
    |  Include:      SCCERR.H
    |  Environment:  Portable
    |  Function:     Unified error codes for
    |                Outside In Viewer Technology Specification 4.0
    |    
     }
{$ifndef USE_SCCERR_2}
{$ifndef _SCCERR_H}

  const
     SCCERR_USEROFFSET = $00000100;     
  {*****************************************************
  |  NOTICE!
  |  DO NOT renumber the errors below!
  |
  |***************************************************** }  {
  |  G E N E R A L   E R R O R S 
   }
  { No error                                                       }
     SCCERR_OK = 0;     
  { An unknown error has occurred                                  }
     SCCERR_UNKNOWN = 18;     
  { An unknown error has occurred                                  }
     SCCERR_LEG_UNKNOWNFAILURE = 8;     
  { One or more of the passed in parameters is invalid             }
     SCCERR_BADPARAM = 15;     
  { User aborted or exception trapped                              }
     SCCERR_ABORT = 32;     
  { User cancelled                                                 }
     SCCERR_CANCEL = 20;     
  { Module has not yet been initialized                            }
     SCCERR_NOINIT = 21;     
  { SCCVW_MACINIT message process failed                           }
     SCCERR_MACINITFAILED = 28;     
     SCCERR_MESSAGEHANDLED = 24;     
     SCCERR_NOITEM = 37;     
  { The requested item could not be found                          }
     SCCERR_NONEFOUND = 25;     
     SCCERR_MORE = 35;     
  { The callback function was not handled or does not exist        }
     SCCERR_NOTHANDLED = 50;     
  { Operating system generated error                               }
     SCCERR_SYSTEM = $080;     
  { Process creation error                                         }
     SCCERR_PROCCREATE = $081;     
  { Process destruction error                                      }
     SCCERR_PROCDESTROY = $082;     
  { Process exceeded its allotted run time.                        }
     SCCERR_PROCTIMEOUT = $083;     
  { Assertion failure                                              }
     SCCERR_ASSERTIONFAILED = $084;     
  { Generated by UTDEBUGERROR macro                                }
     SCCERR_DEBUGERROR = $085;     
  { No changes were made                                           }
     SCCERR_NOCHANGE = $086;     
  { Failed to open display (XOpenDisplay failed)                   }
     SCCERR_DISPLAYOPENFAILED = $087;     
  { Data sent was recognized, but in an unexpected format          }
     SCCERR_WRONGDATAFORMAT = $088;     
  { Specified index is outside the legal range                     }
     SCCERR_INDEXOUTOFBOUNDS = $089;     
  { Error destroying a process                                     }
     SCCERR_PROCESSDESTROY = $090;     
  { Satisfying the call would require blocking the thread          }
     SCCERR_WOULDBLOCK = $091;     
  { 
  |  M E M O R Y   E R R O R S
   }
  { Not enough memory for an allocation                            }
     SCCERR_ALLOCFAILED = 13;     
  { Insufficient memory to perform the operation                   }
     SCCERR_OUTOFMEMORY = 30;     
  { The provided buffer is not large enough to contain the result  }
     SCCERR_INSUFFICIENTBUFFER = 46;     
  { A memory leak was detected                                     }
     SCCERR_MEMORYLEAK = 48;     
     SCCERR_MEMTABLEFULL = $100;     
     SCCERR_INVALIDHANDLE = $101;     
     SCCERR_NULLHANDLE = $102;     
     SCCERR_LOCKEDHANDLE = $103;     
     SCCERR_UNLOCKEDHANDLE = $104;     
     SCCERR_NULLPOINTER = $105;     
  {
  |  F I L E   E R R O R S 
   }
  { The file could not be opened                                   }
     SCCERR_FILEOPENFAILED = 7;     
  { The file is corrupt                                            }
     SCCERR_BADFILE = 9;     
  { The file is empty                                              }
     SCCERR_EMPTYFILE = 10;     
  { The file is password protected or encrypted                    }
     SCCERR_PROTECTEDFILE = 11;     
  { The filter could not open additional files needed to view      }
     SCCERR_SUPFILEOPENFAILED = 12;     
  { No file is currently open                                      }
     SCCERR_NOFILE = 16;     
  { Unexpected EOF in file                                         }
     SCCERR_EOF = 31;     
  { Error while creating file                                      }
     SCCERR_FILECREATE = 34;     
  { File has changed unexpectedly                                  }
     SCCERR_FILECHANGED = 38;     
  { Error writing to file                                          }
     SCCERR_FILEWRITEFAILED = 47;     
  { The file is protected by DRM tools.                            }
     SCCERR_DRMFILE = 49;     
  { File handle is invalid                                         }
     SCCERR_INVALIDFILEHANDLE = $140;     
     SCCERR_OPENINPUTFAILED = $141;     
     SCCERR_FILECOPYFAILED = $142;     
     SCCERR_FILENOTAVAILABLE = $143;     
  { The requested record has been deleted                          }
     SCCERR_RECORDDELETED = $144;     
  { The specified path does not exist                              }
     SCCERR_INVALIDPATH = $145;     
  { The specified spec is not valid.                               }
     SCCERR_INVALIDSPEC = $146;     
  { dwInfoID parameter to IOGetInfo() was invalid                  }
     SCCERR_BADINFOID = $147;     
     SCCERR_SEEKOUTOFRANGE = $148;     
  { Processing of archive file entry has resulted in a file whose full name exceeds OS limits.  }
     SCCERR_BADFILENAME = $149;     
  { The locator refers to an external URL that can not be accessed  }
     SCCERR_EXTERNALURLREFERENCE = $150;     
  { File size exceeds the maximum size that can be processed  }
     SCCERR_FILESIZE = $151;     
  { The object links to file and can not be extract from the file  }
     SCCERR_LINKTOFILE = $152;     
  { The file is not archive file and can not be opened when the archive only mode is set  }
     SCCERR_NOTARCHIVEFILE = $153;     
  { The file is not supported archive file and can not be opened when the archive only mode is set  }
     SCCERR_NOTSUPPORTEDARCHIVEFILE = $154;     
  { The hDoc created as the archive only mode and can not be used in the function  }
     SCCERR_INVALIDHDOC = $155;     
  {
  |  F I L E   I D   E R R O R S 
   }
  { The passed or generated file ID is invalid                     }
     SCCERR_INVALIDID = 1;     
  { The file is in an unsupported format                           }
     SCCERR_UNSUPPORTEDFORMAT = 14;     
  { Continue at 0x180  }
  {
  |  F I L T E R   E R R O R S
   }
  { No filter available for this file type                         }
     SCCERR_NOFILTER = 4;     
  { The filter DLL for this file type could not be loaded.         }
     SCCERR_FILTERLOADFAILED = 2;     
  { This error sometimes appears if the filter was                 }
  { accidentally built in debug mode and the target machine does   }
  { not have MSVCRTD.DLL.                                          }
  { The filter DLL could not allocate enough memory                }
     SCCERR_FILTERALLOCFAILED = 3;     
  { Filter timed out                                               }
     SCCERR_FILTERTIMEOUT = 27;     
  { Exception in filter: access violation                          }
     SCCERR_FILTEREXCEPTACCESS = 39;     
  { Exception in filter: divide by zero                            }
     SCCERR_FILTEREXCEPTZERO = 40;     
  { Exception in filter: other exception                           }
     SCCERR_FILTEREXCEPTOTHER = 41;     
  { Filter failed scramble test                                    }
     SCCERR_FILTERSCRAMBLEERROR = 42;     
  { Bitmap tile size exceeded maximum                              }
     SCCERR_FILTERTILEMAXEXCEEDED = 43;     
  { Protocol mismatch between adjacent pipeline components       }
     SCCERR_PROTOCOLMISMATCH = $1C0;     
  { Format mismatch between adjacent pipeline components         }
     SCCERR_FORMATMISMATCH = $1C1;     
  { Last component in pipeline is not active                     }
     SCCERR_ACTIVECOMPONENT = $1C2;     
  { Returned by passive components at the end of a section       }
     SCCERR_ENDOFSECTION = $1C3;     
  { Returned by passive components at the end of the document    }
     SCCERR_ENDOFDOCUMENT = $1C4;     
  { No export filter available to translate to html.  }
     SCCERR_NOHTMLEXPORTFILTER = $1C5;     
  { No export filter available to translate to selected graphic type.  }
     SCCERR_NOGRAPHICEXPORTFILTER = $1C6;     
  { Either the OCR bridge module or the OCR engine is missing.  }
     SCCERR_OCRMISSING = $1C7;     
  { FAERR_STREAMOPENFAILED                                       }
     SCCERR_STREAMOPENFAILED = $1C8;     
  { FAERR_INITFAILED                                             }
     SCCERR_FAINITFAILED = $1C9;     
  { FAERR_NOMORE                                                 }
     SCCERR_FANOMORE = $1CA;     
  { FAERR_REBUILD                                                }
     SCCERR_FAREBUILD = $1CB;     
  {
  |  D I S P L A Y   E N G I N E   E R R O R S
   }
  { A display engine is not available for this file type           }
     SCCERR_NODISPLAYENGINE = 19;     
  { The display window could not be initialized                    }
     SCCERR_DISPLAYINITFAILED = 5;     
  { No data to render - used by MULTIMEDIA display engine          }
     SCCERR_NODATATORENDER = 51;     
  { Continue at 0x200  }
  { 
  |  C H U N K E R   E R R O R S
   }
  { The chunker (SCCCH.DLL) could not be initialized               }
     SCCERR_CHUNKERINITFAILED = 6;     
  { The requested data is not yet available                        }
     SCCERR_DATANOTAVAILABLE = 45;     
  { An expired data point has been requested in a    }
     SCCERR_XCHSEQUENTIALACCESSVIOLATION = $240;     
  { sequential access situation	  			        }
  { any of a number of errors which are currently being called   }
     SCCERR_CHUNKERFAILURE = $241;     
  { "Out Of Memory"                                              }
  { Continue at 0x242  }
  {
  |  V I E W E R   E R R O R S 
   }
  { Viewer bailed out                                              }
     SCCERR_VIEWERBAIL = 36;     
  { Continue at 0x280  }
  {
  |  C H A R M A P   E R R O R S
   }
  { Character mapping routines failed                              }
     SCCERR_CHARMAPFAILED = 33;     
  { Continue at 0x2C0  }
  { 
  |  P R I N T I N G   E R R O R S
   }
  { Page just drawn is the last in the file                        }
     SCCERR_LASTPAGE = 22;     
  { Requested page doesn't exist or isn't yet available            }
     SCCERR_NOPAGE = 23;     
  { Another print process is already in progress                   }
     SCCERR_OTHERPRINTING = 29;     
  { Continue at 0x300  }
  { 
  |  F E A T U R E   E R R O R S
   }
  { This feature is not supported in this build                    }
     SCCERR_FEATURENOTAVAIL = 17;     
     SCCERR_RAWTEXTDISABLED = 26;     
  { encountered "unlicensed" LZW or JPG compression              }
     SCCERR_UNSUPPORTEDCOMPRESSION = 270;     
  { Continue at 0x340  }
  {
  |  R F A   E R R O R S
   }
  { RFA remote data error                                          }
     SCCERR_DATAREMOTEERROR = 44;     
  { Continue at 0x380  }
  {
  |  E X C E P T I O N S
   }
  { An exception has occurred                           }
     SCCERR_EXCEPTION = $3C0;     
  { Access violation                                    }
     SCCERR_EXCEPT_ACCESS_VIOLATION = $3C1;     
  { Breakpoint encountered                              }
     SCCERR_EXCEPT_BREAKPOINT = $3C2;     
  { Data misalignment                                   }
     SCCERR_EXCEPT_DATATYPE_MISALIGNMENT = $3C3;     
  { Trace trap single step indicated                    }
     SCCERR_EXCEPT_SINGLE_STEP = $3C4;     
  { Out of bounds array element referenced              }
     SCCERR_EXCEPT_ARRAY_BOUNDS_EXCEEDED = $3C5;     
  { Floating point value is denormal                    }
     SCCERR_EXCEPT_FLT_DENORMAL_OPERAND = $3C6;     
  { Floating point divide by zero                       }
     SCCERR_EXCEPT_FLT_DIVIDE_BY_ZERO = $3C7;     
  { Result cannot be represented as decimal fraction    }
     SCCERR_EXCEPT_FLT_INEXACT_RESULT = $3C8;     
  { General floating point exception                    }
     SCCERR_EXCEPT_FLT_INVALID_OPERATION = $3C9;     
  { Floating point exponent overflow                    }
     SCCERR_EXCEPT_FLT_OVERFLOW = $3CA;     
  { Floating point stack underflow or overflow          }
     SCCERR_EXCEPT_FLT_STACK_CHECK = $3CB;     
  { Floating point exponent underflow                   }
     SCCERR_EXCEPT_FLT_UNDERFLOW = $3CC;     
  { Integer divide by zero                              }
     SCCERR_EXCEPT_INT_DIVIDE_BY_ZERO = $3CD;     
  { Integer overflow                                    }
     SCCERR_EXCEPT_INT_OVERFLOW = $3CE;     
  { Priveleged instruction                              }
     SCCERR_EXCEPT_PRIV_INSTRUCTION = $3CF;     
  { A noncontinuable exception has occurred             }
     SCCERR_EXCEPT_NONCONTINUABLE = $3D0;     
  { Unknown exception type                              }
     SCCERR_EXCEPT_UNKNOWN = $3D1;     
  { Stack Buffer Overrun detected                       }
     SCCERR_STACK_BUFFER_OVERRUN = $3D2;     
  {
  | U T  E X C E P T I O N S
   }
     SCCERR_GPFAULT = 100;     
     SCCERR_DIVIDEBYZERO = 101;     
     SCCERR_OTHEREXCEPTION = 102;     
  {
  |  T E S T   E R R O R S
   }
  { The requested test is not available                 }
     SCCERR_TESTNOTAVAILABLE = $400;     
  { The test timed out                                  }
     SCCERR_TESTTIMEOUT = $401;     
  { Unable to create binary file                        }
     SCCERR_CREATEBINFAILED = $402;     
  { Unable to open binary file                          }
     SCCERR_OPENBINFAILED = $403;     
  { Unable to write to binary file                      }
     SCCERR_WRITEBINFAILED = $404;     
  { Unable to read from binary file                     }
     SCCERR_READBINFAILED = $405;     
  { Unable to open dump file                            }
     SCCERR_OPENDUMPFAILED = $406;     
  { Chunker compare failed                              }
     SCCERR_COMPAREFAILED = $407;     
  { Chunkers had different run counts                   }
     SCCERR_CHUNKERRUNMISMATCH = $408;     
  { Chunkers had different run sizes                    }
     SCCERR_CHUNKERSIZEMISMATCH = $409;     
  { Chunker failure                                     }
     SCCERR_CHUNKERFAILED = $40A;     
  { Chunker run count overflow                          }
     SCCERR_CHUNKEROVERRUN = $40B;     
  { General Compression failure                         }
     SCCERR_COMPRESSIONFAILED = $40C;     
  { General stream bailout                              }
     SCCERR_STREAMBAIL = $40D;     
     SCCERR_MISSINGELEMENT = $40E;     
  { Test is complete                                    }
     SCCERR_TESTCOMPLETE = $40F;     
     SCCERR_TESTMODESWITCH = $410;     
  { A baseline file was not found for a compare file    }
     SCCERR_BASELINEFILENOTFOUND = $411;     
  { A compare file was not found for a baseline file    }
     SCCERR_COMPAREFILENOTFOUND = $412;     
  { Technology is not available                         }
     SCCERR_TECHNOTAVAILABLE = $420;     
  { Both the baseline and compare files are empty       }
     SCCERR_TESTFILESEMPTY = $421;     
  {
  |  C O M M U N I C A T I O N S   E R R O R S
   }
  { Received an unexpected response                     }
     SCCERR_INVALIDRESPONSE = $500;     
  { Communications timeout                              }
     SCCERR_COMMTIMEOUT = $501;     
  { General communications error                        }
     SCCERR_COMMUNKNOWN = $502;     
  { Connection refused                                  }
     SCCERR_CONNECTIONREFUSED = $503;     
  { Communications fault                                }
     SCCERR_COMMFAULT = $504;     
  { Host or network is down                             }
     SCCERR_CONNECTIONDOWN = $505;     
  { Host or network is unreachable                      }
     SCCERR_CONNECTIONUNREACHABLE = $506;     
  { Unexpected disconnection                            }
     SCCERR_DISCONNECTED = $507;     
  { Synchronization error                               }
     SCCERR_SYNCHRONIZE = $508;     
  { 
  |  H T M L  E X P O R T  E R R O R S
  |
  | [U] = unused
   }
  { First HX error code                                               }
     SCCERR_BI_FIRSTERROR = $600;     
  { General error has occured [U]                                     }
     SCCERR_BI_GENERAL = $600;     
  { Element specified does not conform to the parse tree structure    }
     SCCERR_BI_TREE = $601;     
  { an integer or current/next/previous token was expected            }
     SCCERR_BI_INVALID_VAL = $602;     
  { no error [U]                                                      }
     SCCERR_BI_NONE = $603;     
  { ## /xx tag not found                                            }
     SCCERR_BI_ENDMACRO = $604;     
     SCCERR_BI_ENDBARNEY = $604;     
  { start brace "" expected and not found [U]                        }
     SCCERR_BI_START = $605;     
     SCCERR_BI_LT = $605;     
  { equal sign "=" expected and not found                             }
     SCCERR_BI_EQ = $606;     
  { end brace "" expected and not found                              }
     SCCERR_BI_END = $607;     
     SCCERR_BI_GT = $607;     
  { Error parsing "ACTION = "statements [U]                           }
     SCCERR_BI_ACTION = $608;     
  { section not found                                                 }
     SCCERR_BI_SECTION = $609;     
     SCCERR_BI_BARNEY = $609;     
  { Error parsing "ELEMENT = " statement                              }
     SCCERR_BI_ELEMENT = $60A;     
  { Error parsing "LINK = " statement [U]                             }
     SCCERR_BI_LINK = $60B;     
  { Error parsing "TAG = " statement [U]                              }
     SCCERR_BI_TAG = $60C;     
  { Error parsing "TEMPLATE = " statement                             }
     SCCERR_BI_TEMPLATE = $60D;     
  { Error parsing "TYPE = " statement                                 }
     SCCERR_BI_TYPE = $60E;     
  { Error parsing "NAME = " statement [U]                             }
     SCCERR_BI_TYPENAME = $60F;     
  { Error parsing "ACTION = DEFINE" statement [U]                     }
     SCCERR_BI_DEFINE = $610;     
  { Error in document data                                            }
     SCCERR_BI_DOCUMENT = $611;     
  { Error parsing GENLINK statement                                   }
     SCCERR_BI_GENLINK = $612;     
  { Error parsing INSERT statement                                    }
     SCCERR_BI_INSERT = $613;     
  { Error parsing REPEAT statement                                    }
     SCCERR_BI_REPEAT = $614;     
  { Error in tree transition Element [U]                              }
     SCCERR_BI_CHKTRAN = $615;     
  { Error in allocating memory in MiscBuffer [U]                      }
     SCCERR_BI_ALLOC = $616;     
  { Error - invalid command [U]                                       }
     SCCERR_BI_INVALIDCMD = $617;     
  { Invalid error number [U]                                          }
     SCCERR_BI_INVALIDERRNUM = $618;     
  { Error in converting document element [U]                          }
     SCCERR_BI_HANDLEELEM = $619;     
  { Error writing normal text from input file to an output file [U]   }
     SCCERR_BI_ASISOUTTEXT = $61A;     
  { Error writing parser-generated HTML text to an output file [U]    }
     SCCERR_BI_OUTTEXT = $61B;     
  { Error opening template file                                       }
     SCCERR_BI_NOTEMPLATE = $61C;     
  { Error opening output file [U]                                     }
     SCCERR_BI_OUTFILEFAIL = $61D;     
  { No ## /repeat tag found                                         }
     SCCERR_NOENDREPEAT = $61E;     
  { No ## /if tag found                                             }
     SCCERR_NOENDIF = $61F;     
  { No ## /ignore tag found                                         }
     SCCERR_NOENDIGNORE = $620;     
  { Element specified in repeat is non-repeatable element             }
     SCCERR_NONREPEAT = $621;     
  { Repeat element ended on the index [U]                             }
     SCCERR_REPEATENDONINDEX = $622;     
  { If element ended on the index [U]                                 }
     SCCERR_IFENDONINDEX = $623;     
  { Insert element ended on the index [U]                             }
     SCCERR_INSERTENDONINDEX = $624;     
  { No element was given                                              }
     SCCERR_NOELEMENT = $625;     
  { Invalid ## tag  [U]                                               }
     SCCERR_INVALIDTAG = $626;     
  { End ## /.. with no corresponding start ## ..                  }
     SCCERR_NOSTARTMACRO = $627;     
     SCCERR_NOSTARTTAG = $627;     
  { Document type given is not valid                                  }
     SCCERR_INVALIDTYPE = $628;     
  { No value given for sections.x.type                                }
     SCCERR_NOVALUE = $629;     
  { No condition given or missing ''                                 }
     SCCERR_NOCONDITION = $62A;     
  { Invalid parameter in ## link macro                                }
     SCCERR_INVALIDLINKPARAM = $62B;     
  { Missing all parameters to link macro                              }
     SCCERR_NOLINKPARAM = $62C;     
  { Count or Value element can only be followed by ''                }
     SCCERR_BADCOUNTORVALUE = $62D;     
  { ## else not preceded by ## if...                              }
     SCCERR_INVALIDELSE = $62E;     
  { Invalid parameter in if condition                                 }
     SCCERR_INVALIDCOND = $62F;     
  { The creation of the default template failed.                      }
     SCCERR_TEMPLATECREATE = $630;     
  { The element exceeded the maximum allowable number of elements     }
     SCCERR_MAXELEMSPASSED = $631;     
  { No type was given for sections.x.type                             }
     SCCERR_NOTYPE = $632;     
  { The element is a custom element. Basically, this is a flag.       }
     SCCERR_CUSTOMELEMENT = $633;     
  { ## elseif not preceded by ## if...                            }
     SCCERR_INVALIDELSEIF = $634;     
  { Pragma.CSSFile required and not present                           }
     SCCERR_BI_CSSPRAGMA = $635;     
  { Invalid anchor value                                              }
     SCCERR_BI_ANCHOR = $636;     
  { Invalid label value                                               }
     SCCERR_BI_LABEL = $637;     
  { Template-generated text exceeds the deck size                     }
     SCCERR_BI_DECKSIZEEXCEEDED = $638;     
  { Macro not supported in this HTML flavor                           }
     SCCERR_BI_UNSUPPORTEDMACRO = $639;     
  { Internal Export Filter Error                                      }
     SCCERR_INTERNALEXPORTFILTER = $63A;     
  { Error parsing the template                                        }
     SCCERR_TEMPLATEPARSE = $63B;     
  { Error generating output file                                      }
     SCCERR_OUTPUTFILE = $63C;     
  { Internal element tree error                                       }
     SCCERR_INTERNALELEMENT = $63D;     
  { Internal preview document error                                   }
     SCCERR_INTERNALPREVIEW = $63E;     
  { Internal process document error                                   }
     SCCERR_INTERNALPROCESS = $63F;     
  { Non-fatal error:  we've reached the insertion truncation limit    }
     SCCERR_TRUNCATIONLIMITREACHED = $640;     
  { ## repeat statement found in unit header or footer              }
     SCCERR_NONBREAKINGREPEAT = $641;     
  { this template cannot be used with a nonzero deck size             }
     SCCERR_NONBREAKINGTEMPLATE = $642;     
  { invalid attribute                                                 }
     SCCERR_INVALIDATTRIBUTE = $643;     
  { invalid or missing attribute value                                }
     SCCERR_INVALIDATTRIBVALUE = $644;     
  { malformed unit - check for matching header and footer tags        }
     SCCERR_MALFORMEDUNIT = $645;     
  { Text buffer size is too small                                     }
     SCCERR_TEXTBUFFERTOOSMALL = $646;     
  { Buffer size is too small to export graphics                       }
     SCCERR_BUFFERTOOSMALLFORGRAPHICS = $647;     
  { Internal export memory utility error                              }
     SCCERR_INTERNALEXMU = $648;     
  { Internal export list management error                             }
     SCCERR_INTERNALEXLM = $649;     
  { Internal export para error                                        }
     SCCERR_INTERNALPARA = $64A;     
  { Internal export style error                                       }
     SCCERR_INTERNALSTYLE = $64B;     
  { Internal export table error                                       }
     SCCERR_INTERNALTABLE = $64C;     
  { Internal export tags error                                        }
     SCCERR_INTERNALTAGS = $64D;     
  { Internal export graphics error                                    }
     SCCERR_INTERNALGRAPHICS = $64E;     
  { Non-fatal error:  we've reached the grid cell truncation limit    }
     SCCERR_GRIDCELLLIMITREACHED = $64F;     
  { Internal export tag id error									   }
     SCCERR_INTERNALTAGID = $650;     
  { Internal export object locator Id error						   }
     SCCERR_INTERNALLOCATIONID = $651;     
  { Internal export spreadsheet cell error							   }
     SCCERR_INTERNALSSCELL = $652;     
  { Internal export spreadsheet error								   }
     SCCERR_INTERNALEMPTYSHEET = $653;     
  { Internal document tree error                                      }
     SCCERR_INTERNALDOCUMENT = $654;     
  { Section no data error                                             }
     SCCERR_SECTNODATA = $655;     
  { Last HX error code                                                }
     SCCERR_BI_LASTERROR = $655;     
  { 
  |  I M A G E  E X P O R T  E R R O R S
  |
  | 
   }
  { The start page value is larger than the number of pages in the document  }
     SCCERR_STARTPAGEERROR = $700;     
  { The start page value is larger than the end page value  }
     SCCERR_ENDPAGEERROR = $701;     
     SCCERR_WATERMARKWILLNOTFITTARGET = $702;     
     SCCERR_WATERMARKTYPENOTSUPPORTED = $703;     
  {
  |
  |  X T R E E   E R R O R S
  |
   }
  { Node is already released and may not be accessed  }
     SCCERR_NODERELEASED = $800;     
  { Node is already attached to a parent - can't attach again  }
     SCCERR_NODEATTACHED = $801;     
  { Node is not yet attached to a parent  }
     SCCERR_NODENOTATTACHED = $802;     
  { No more children may be attached to the node  }
     SCCERR_ALLCHILDRENATTACHED = $803;     
  { Attributes may not be changed  }
     SCCERR_NODEATTRIBUTESDONE = $804;     
  { Attempted to create a new ID with the same string value as an existing ID  }
     SCCERR_DUPLICATEID = $805;     
  { Attempted to change the ID string of a node  }
     SCCERR_IDASSIGNED = $806;     
  { Attributes may not be accessed by the consumer  }
     SCCERR_NODEATTRIBUTESNOTDONE = $807;     
  { The node is from a different tree  }
     SCCERR_DIFFERENTTREE = $808;     
  {
  | 
  | D Y N A M I C  L O A D  L I B R A R Y  E R R O R S
  |
   }
     SCCERR_ANNOLOAD = $A00;     
     SCCERR_ANNOFUNCTION = $A01;     
  {
  | Character set map bin file error
   }
     SCCERR_NOCHARSETMAPBINFILE = $900;     
  {
  |   Win32V/Output Solution Errors
   }
     SCCERR_NOGDFONTS = $B00;     
     SCCERR_OUTPUTSOLUTIONLOADFAILED = $B01;     
     SCCERR_INVALIDFONTDIR = $0B02;     
     SCCERR_NOVALIDFONTS = $0B03;     
  {
  |  OCR Export Errors
   }
     SCCERR_OCR_UNKNOWNERR = $C00;     
     SCCERR_OCR_LICENCEFAIL = $C01;     
     SCCERR_OCR_INVALIDTECH = $C02;     
     SCCERR_OCR_INVALIDQUAL = $C03;     
     SCCERR_OCR_LOADFAILED = $C04;     
     SCCERR_OCR_INPUTFAILURE = $C05;     
     SCCERR_OCR_FILETOOBIG = $C06;     
  {
  |  File Access Errors
   }
  { bad credentials supplied for access to file contents  }
     SCCERR_BADCREDENTIALS = $d00;     

{$endif}
  { _SCCERR_H  }
{$endif}
  { USE_SCCERR_2  }

implementation


end.
